---
- name: 1Password
  identifier:
    kind: exe
    id: 1Password.exe
  float_identifiers:
    - kind: exe
      id: 1Password.exe
- name: AutoHotkey
  identifier:
    kind: exe
    id: AutoHotkeyU64.exe
  options:
    - tray_and_multi_window
  float_identifiers:
    - kind: title
      id: Window Spy
- name: Beeper
  identifier:
    kind: exe
    id: Beeper.exe
  options:
    - border_overflow
    - tray_and_multi_window
- name: Calculator
  identifier:
    kind: title
    id: Calculator
  float_identifiers:
    - kind: title
      id: Calculator
- name: Credential Manager UI Host
  identifier:
    kind: exe
    id: CredentialUIBroker.exe
  float_identifiers:
    - kind: exe
      id: CredentialUIBroker.exe
      comment: Targets the Windows popup prompting you for a PIN instead of a password on 1Password etc.
- name: Discord
  identifier:
    kind: exe
    id: Discord.exe
  options:
    - border_overflow
    - tray_and_multi_window
- name: Epic Games Launcher
  identifier:
    kind: exe
    id: EpicGamesLauncher.exe
  options:
    - border_overflow
    - tray_and_multi_window
- name: GOG Galaxy
  identifier:
    kind: exe
    id: GalaxyClient.exe
  options:
    - border_overflow
    - force
    - tray_and_multi_window
  float_identifiers:
    - kind: class
      id: Chrome_RenderWidgetHostHWND
      comment: Targets a hidden window spawned by GOG Galaxy
- name: Google Chrome
  identifier:
    kind: exe
    id: chrome.exe
  options:
    - tray_and_multi_window
- name: IntelliJ IDEA
  identifier:
    kind: exe
    id: idea64.exe
  options:
    - object_name_change
    - tray_and_multi_window
  float_identifiers:
    - kind: class
      id: SunAwtDialog
      comment: Targets JetBrains IDE popups and floating windows
- name: Microsoft Excel
  identifier:
    kind: exe
    id: EXCEL.EXE
  options:
    - border_overflow
    - layered
  float_identifiers:
    - kind: class
      id: _WwB
      comment: Targets a hidden window spawned by Microsoft Office applications
- name: Microsoft Outlook
  identifier:
    kind: exe
    id: OUTLOOK.EXE
  options:
    - border_overflow
    - layered
  float_identifiers:
    - kind: class
      id: _WwB
      comment: Targets a hidden window spawned by Microsoft Office applications
- name: Microsoft PowerPoint
  identifier:
    kind: exe
    id: POWERPNT.EXE
  options:
    - border_overflow
    - layered
  float_identifiers:
    - kind: class
      id: _WwB
      comment: Targets a hidden window spawned by Microsoft Office applications
- name: Microsoft Teams
  identifier:
    kind: exe
    id: Teams.exe
  float_identifiers:
    - kind: title
      id: Microsoft Teams Notifications
      comment: Target Teams pop-up notification windows
- name: Microsoft Word
  identifier:
    kind: exe
    id: WINWORD.EXE
  options:
    - border_overflow
    - layered
  float_identifiers:
    - kind: class
      id: _WwB
      comment: Targets a hidden window spawned by Microsoft Office applications
- name: Mozilla Firefox
  identifier:
    kind: exe
    id: firefox.exe
  options:
    - object_name_change
    - tray_and_multi_window
- name: NiceHash Miner
  identifier:
    kind: exe
    id: nhm_app.exe
  options:
    - border_overflow
    - force
- name: Obsidian
  identifier:
    kind: exe
    id: Obsidian.exe
  options:
    - border_overflow
    - force
- name: Paradox Launcher
  identifier:
    kind: exe
    id: Paradox Launcher.exe
  float_identifiers:
    - kind: exe
      id: Paradox Launcher.exe
- name: PyCharm
  identifier:
    kind: exe
    id: pycharm64.exe
  options:
    - object_name_change
    - tray_and_multi_window
  float_identifiers:
    - kind: class
      id: SunAwtDialog
      comment: Targets JetBrains IDE popups and detached windows
- name: QuickLook
  identifier:
    kind: exe
    id: QuickLook.exe
  float_identifiers:
    - kind: exe
      id: QuickLook.exe
- name: RoundedTB
  identifier:
    kind: exe
    id: RoundedTB.exe
- name: Signal
  identifier:
    kind: exe
    id: signal.exe
  options:
    - tray_and_multi_window
- name: Slack
  identifier:
    kind: exe
    id: slack.exe
  options:
    - border_overflow
    - force
    - tray_and_multi_window
- name: Spotify
  identifier:
    kind: exe
    id: Spotify.exe
  options:
    - border_overflow
    - tray_and_multi_window
- name: Steam
  identifier:
    kind: class
    id: vguiPopupWindow
  options:
    - border_overflow
- name: TouchCursor
  identifier:
    kind: exe
    id: tcconfig.exe
  options:
    - tray_and_multi_window
  float_identifiers:
    - kind: exe
      id: tcconfig.exe
- name: TranslucentTB
  identifier:
    kind: exe
    id: TranslucentTB.exe
  options:
    - tray_and_multi_window
- name: Windows Explorer
  identifier:
    kind: exe
    id: explorer.exe
  float_identifiers:
    - kind: class
      id: OperationStatusWindow
      comment: Targets copy/move operation windows
    - kind: title
      id: Control Panel
- name: Zoom
  identifier:
    kind: exe
    id: Zoom.exe
  float_identifiers:
    - kind: exe
      id: Zoom.exe
- name: qBittorrent
  identifier:
    kind: exe
    id: qbittorrent.exe
  options:
    - tray_and_multi_window
- name: ueli
  identifier:
    kind: exe
    id: ueli.exe
  options:
    - tray_and_multi_window
  float_identifiers:
    - kind: exe
      id: ueli.exe
