- name: Beeper
  identifier:
    kind: exe
    id: Beeper.exe
  options:
    - border_overflow
    - tray_and_multi_window
- name: Discord
  identifier:
    kind: exe
    id: Discord.exe
  options:
    - border_overflow
    - tray_and_multi_window
- name: Google Chrome
  identifier:
    kind: exe
    id: chrome.exe
  options:
    - tray_and_multi_window
- name: IntelliJ IDEA
  identifier:
    kind: exe
    id: idea64.exe
  options:
    - object_name_change
    - tray_and_multi_window
  float_identifiers:
    - kind: class
      id: SunAwtDialog
- name: Microsoft Excel
  identifier:
    kind: exe
    id: EXCEL.EXE
  options:
    - border_overflow
    - layered
  float_identifiers:
    - kind: class
      id: _WwB
- name: Microsoft Word
  identifier:
    kind: exe
    id: WINWORD.EXE
  options:
    - border_overflow
    - layered
  float_identifiers:
    - kind: class
      id: _WwB
- name: Mozilla Firefox
  identifier:
    kind: exe
    id: firefox.exe
  options:
    - object_name_change
    - tray_and_multi_window
- name: PyCharm
  identifier:
    kind: exe
    id: pycharm64.exe
  options:
    - object_name_change
    - tray_and_multi_window
  float_identifiers:
    - kind: class
      id: SunAwtDialog
- name: Slack
  identifier:
    kind: exe
    id: slack.exe
  options:
    - border_overflow
    - force
    - tray_and_multi_window
- name: Spotify
  identifier:
    kind: exe
    id: Spotify.exe
  options:
    - border_overflow
    - tray_and_multi_window
- name: QuickLook
  identifier:
    kind: exe
    id: QuickLook.exe
  float_identifiers:
    - kind: exe
      id: QuickLook.exe
- name: Calculator
  identifier:
    kind: title
    id: Calculator
  float_identifiers:
    - kind: title
      id: Calculator
- name: AhkWindowSpy
  identifier:
    kind: title
    id: Window Spy
  float_identifiers:
    - kind: title
      id: Window Spy
- name: RoundedTB
  identifier:
    kind: exe
    id: RoundedTB.exe
  options:
    - tray_and_multi_window
- name: TranslucentTB
  identifier:
    kind: exe
    id: TranslucentTB.exe
  options:
    - tray_and_multi_window
- name: TouchCursor
  identifier:
    kind: exe
    id: tcconfig.exe
  options:
    - tray_and_multi_window
  float_identifiers:
    - kind: exe
      id: tcconfig.exe
- name: Microsoft Teams
  identifier:
    kind: exe
    id: Teams.exe
  float_identifiers:
    - kind: title
      id: Microsoft Teams Notifications